### ISSUE TITLE
发布文章 图片粘贴上传

### ISSUE THREAD

**Issue by Q-yt** [fengfengzhidao/fengfeng_blog#4]
请问，在发布文章页面的markdown编辑器上 如何实现图片的粘贴上传？

**Comment by fengfengzhidao** [comment]
这个应该需要自己实现粘贴事件



***@***.***
 
发件人： Q-yt
发送时间： 2023-01-18 10:39
收件人： fengfengzhidao/fengfeng_blog
抄送： Subscribed
主题： [fengfengzhidao/fengfeng_blog] 发布文章 图片粘贴上传 (Issue #4)
请问，在发布文章页面的markdown编辑器上 如何实现图片的粘贴上传？

**Comment by fengfengzhidao** [comment]
现已支持
